#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

import coremltools as ct
import torch

from hexplode_nn import HexplodePolicyValueNet


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export Hexplode policy-value checkpoint to CoreML.")
    parser.add_argument(
        "--checkpoint",
        type=str,
        default="tools/outputs/hexplode_policy_value.pt",
        help="PyTorch checkpoint generated by hexplode_train_nn.py",
    )
    parser.add_argument(
        "--out",
        type=str,
        default="tools/outputs/HexplodePolicy.mlpackage",
        help="Output CoreML package (.mlpackage or .mlmodel)",
    )
    parser.add_argument("--ios-target", type=str, default="15", help="Minimum iOS target for exported model.")
    return parser.parse_args()


def pick_target(version: str):
    if version == "13":
        return ct.target.iOS13
    if version == "14":
        return ct.target.iOS14
    if version == "15":
        return ct.target.iOS15
    if version == "16":
        return ct.target.iOS16
    if version == "17":
        return ct.target.iOS17
    return ct.target.iOS15


def main() -> None:
    args = parse_args()
    checkpoint_path = Path(args.checkpoint)
    out_path = Path(args.out)

    if not checkpoint_path.exists():
        raise FileNotFoundError(f"Checkpoint not found: {checkpoint_path}")

    checkpoint = torch.load(checkpoint_path, map_location="cpu")
    channels = int(checkpoint.get("channels", 64))
    blocks = int(checkpoint.get("blocks", 6))
    board_size = int(checkpoint.get("board_size", 7))
    input_channels = int(checkpoint.get("input_channels", 8))

    model = HexplodePolicyValueNet(
        input_channels=input_channels,
        channels=channels,
        blocks=blocks,
        board_size=board_size,
    )
    model.load_state_dict(checkpoint["state_dict"])
    model.eval()

    sample_input = torch.randn(1, input_channels, board_size, board_size)
    traced = torch.jit.trace(model, sample_input)

    mlmodel = ct.convert(
        traced,
        convert_to="mlprogram",
        minimum_deployment_target=pick_target(args.ios_target),
        inputs=[ct.TensorType(name="input", shape=sample_input.shape)],
        outputs=[
            ct.TensorType(name="policy"),
            ct.TensorType(name="value"),
        ],
    )

    mlmodel.short_description = "Hexplode policy-value network for large-board hard AI."
    mlmodel.input_description["input"] = "Board tensor [1,8,7,7]"
    mlmodel.output_description["policy"] = "Policy logits for flattened 7x7 board"
    mlmodel.output_description["value"] = "Estimated state value in [-1, 1]"

    out_path.parent.mkdir(parents=True, exist_ok=True)
    mlmodel.save(str(out_path))
    print(f"Saved CoreML model: {out_path}")


if __name__ == "__main__":
    main()
